apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-calc
  template:
    metadata:
      labels:
        app: binary-calc
    spec:
      containers:
        - image: gcr.io/sunlit-virtue-379616/binarycalculator
          name: binary-calc
          ports:
            - containerPort: 8080
              name: binary-calc
